services:
  - type: web
    name: frontend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    staticPublishPath: dist
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-m-consiente.onrender.com 